# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TutorialGoogleMapsAnDirection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'	
  pod 'ObjectMapper', '~> 2.2'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod  ‘Alamofire', '~> 4.5'
  pod 'SwiftyJSON'

   # Pods for TutorialGoogleMapsAnDirection

end
